### ISSUE TITLE
Node-Datachannel Error.

### ISSUE THREAD

**Issue by UnyeSpor** [mertushka/haxball.js#49]
Describe the bug
When running a Haxball.js room, the error addRemoteCandidate() called on destroyed peer connection appears multiple times. Initially, it doesn't seem harmful, but after repeated occurrences, it causes game freezes, increased ping, and eventually, the room shuts down entirely. Once the errors stop, the room reopens, but all players have already disconnected.

To Reproduce

Install the necessary package:
npm install haxball.js  
Create a simple room using HBInit().
Let players join and play for some time.
Observe the console logs; after multiple messages, the error appears:
NotFoundError [DOMException]: addRemoteCandidate() called on destroyed peer connection  
If this happens frequently, the game freezes temporarily and eventually crashes.

Expected behavior
The game should not freeze or crash when these errors occur. The peer connections should be managed properly to prevent unnecessary disconnections.

Screenshots

![Image](https://github.com/user-attachments/assets/40d6fb8f-298e-4a2b-a21f-d345399e7be6)

![Image](https://github.com/user-attachments/assets/da1f8a81-a5c4-4979-a78d-8b70468183d9)

![Image](https://github.com/user-attachments/assets/e552bd5a-f3ab-485d-9e60-2b3de0370ea3)

Device (please complete the following information):

Windows Server 2019
Node.js Version: 22.14.0
Haxball.js Version: 2.3.2
Discord.js Version: 14.17.3
Additional context

This issue affects gameplay significantly by causing increased lag and crashes.
As more messages appear in succession, the error worsens, making the game unplayable.
This problem seems to be caused by node-datachannel within haxball.js, as seen in the logs.

I sincerely apologize for opening the previous issue in the wrong place. @mertushka

**Comment by UnyeSpor** [comment]
I have switched to **Haxball.js version 2.2.0**. Since this version does not include **node-datachannel**, my issue has been resolved. I am not experiencing any problems now, and I’m satisfied. However, for the improvement of your API, it would be great if you could fix this bug so that other users don’t encounter the same issue. It’s a really bad situation.

**Comment by mertushka** [comment]
Is there any way to reproduce this? From what I see in the terminal, the error occurs when a player joins and leaves the room at the same time. Can you share your script or a minimal script to reproduce the error logs?

**Comment by mertushka** [comment]
@UnyeSpor This issue should remain open, as `haxball.js` still defaults to the `node-datachannel` library. As one of the contributors to `node-datachannel`, I believe addressing this would be beneficial for the community. It would also be really helpful if you could share a minimal code snippet to reproduce the issue, so I can work on fixing it. In the meantime, please use `haxball.js@3.0.0` with the `@roamhq/wrtc` WebRTC library or other suitable alternatives.

**Comment by imDarvaged** [comment]
hello, the problem persists in this version, at least to me also is present this error after several hours of keeping the room active, after a couple of days the room falls. is there any news mert?
`https://www.haxball.com/play?c=X_bYRyUeU9g
masterPassword : 99273716499127364
Error: libdatachannel error while sending data channel message: DataChannel is closed
    at RTCDataChannel.send (/home/ubuntu/haxball/node_modules/haxball.js/node_modules/node-datachannel/dist/cjs/polyfill/RTCDataChannel.cjs:171:42)
    at ab.ob (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:112:255)
    at bb.ob (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:86:66)
    at Ua.hd (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:142:412)
    at Ua.$d (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:142:305)
    at Ua.Ba (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:141:61)
    at Ua.Jh (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:144:73)
    at Ah.a.nf (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:141:447)
    at e.onmessage (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:112:102)
    at RTCDataChannel.<anonymous> (/home/ubuntu/haxball/node_modules/haxball.js/node_modules/node-datachannel/dist/cjs/polyfill/RTCDataChannel.cjs:84:32)
Error: libdatachannel error while sending data channel message: DataChannel is closed
    at RTCDataChannel.send (/home/ubuntu/haxball/node_modules/haxball.js/node_modules/node-datachannel/dist/cjs/polyfill/RTCDataChannel.cjs:171:42)
    at ab.ob (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:112:255)
    at bb.ob (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:86:66)
    at Ua.hd (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:142:412)
    at Ua.$d (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:142:305)
    at Ua.Ba (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:141:61)
    at Ua.Jh (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:144:73)
    at Ah.a.nf (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:141:447)
    at e.onmessage (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:112:102)
    at RTCDataChannel.<anonymous> (/home/ubuntu/haxball/node_modules/haxball.js/node_modules/node-datachannel/dist/cjs/polyfill/RTCDataChannel.cjs:84:32)
Error: libdatachannel error while sending data channel message: DataChannel is closed
    at RTCDataChannel.send (/home/ubuntu/haxball/node_modules/haxball.js/node_modules/node-datachannel/dist/cjs/polyfill/RTCDataChannel.cjs:171:42)
    at ab.ob (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:112:255)
    at bb.ob (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:86:66)
    at Ua.hd (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:142:412)
    at Ua.Mh (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:146:18)
    at Ua.Jh (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:144:180)
    at Ah.a.nf (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:141:447)
    at e.onmessage (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:112:102)
    at RTCDataChannel.<anonymous> (/home/ubuntu/haxball/node_modules/haxball.js/node_modules/node-datachannel/dist/cjs/polyfill/RTCDataChannel.cjs:84:32)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:831:20)
Error: libdatachannel error while sending data channel message: DataChannel is closed
    at RTCDataChannel.send (/home/ubuntu/haxball/node_modules/haxball.js/node_modules/node-datachannel/dist/cjs/polyfill/RTCDataChannel.cjs:171:42)
    at ab.ob (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:112:255)
    at bb.ob (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:86:66)
    at Ua.hd (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:142:412)
    at Ua.Mh (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:146:18)
    at Ua.Jh (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:144:180)
    at Ah.a.nf (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:141:447)
    at e.onmessage (/home/ubuntu/haxball/node_modules/haxball.js/src/index.js:112:102)
    at RTCDataChannel.<anonymous> (/home/ubuntu/haxball/node_modules/haxball.js/node_modules/node-datachannel/dist/cjs/polyfill/RTCDataChannel.cjs:84:32)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:831:20)

`

**Comment by mertushka** [comment]
@imDarvaged I can’t diagnose the issue just by looking at the error messages. I need a minimal script that reproduces the errors so I can understand what’s happening in the core code.

**Comment by imDarvaged** [comment]
@mertushka Bro you can use any minimal bot you own for sure for some of your own tests, the problem starts occurring with an error every few hours then after two days it crashes

**Comment by murat-dogan** [comment]
@mertushka 

Not sure how to proceed here also.
Let's see first data-channel problem.

**Comment by mertushka** [comment]
This should be fixed in `haxball.js@v3.0.1`. The `node-datachannel` dependency has been updated to `v0.28.0` which addresses the underlying issue with data channel race conditions.

**Comment by imDarvaged** [comment]
I confirm that the latest update of your library is completely broken, causes rtc errors, formatting errors of emoji and texts, leaves ghosts of players in the room causing further errors as well as paradoxically “room is full” even when there are no users... sorry to say but your lib is broken

**Comment by imDarvaged** [comment]
I fixed an error in datachannel but now the utf characters are not correctly shown, replacing them with the classic “?” do you have any ideas?

![Image](https://github.com/user-attachments/assets/06da2b7c-17cc-4ce3-9f80-0c755ee46fdc)
